// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using wspolpracujmy.Data;

#nullable disable

namespace wspolpracujmy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506153000_AddGroupRequestRelationsAndOptionalGroupProject")]
    partial class AddGroupRequestRelationsAndOptionalGroupProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration only adds the optional ProjectId to GroupRequests and relations.
            // The generated target model is not required for applying the migration.
        }
    }
}
