services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wspolpracujmy-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=wspolpracujmy;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
  db:
    image: postgres:18
    container_name: postgres-wspolpracuj.my
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projekt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: