CREATE TABLE "Meeting_types" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" text NOT NULL
);

CREATE TABLE "Tags" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL UNIQUE
);

CREATE TABLE "Users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" character varying(100) NOT NULL,
  "surname" character varying(100) NOT NULL,
  "role" text NOT NULL,
  "login" character varying(100) NOT NULL UNIQUE,
  "password_hash" text NOT NULL
);

CREATE TABLE "Companies" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL UNIQUE,
  "company_name" text NOT NULL,
  "contact_email" text
);

CREATE TABLE "Files" (
  "id" uuid PRIMARY KEY,
  "user_id" integer NOT NULL,
  "group_id" integer,
  "original_name" text NOT NULL,
  "gcs_bucket" text NOT NULL,
  "gcs_object_name" text NOT NULL,
  "content_type" text NOT NULL,
  "size_bytes" bigint NOT NULL,
  "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE "Notifications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "content" text NOT NULL,
  "status" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "link_target" text,
  "group_request_id" integer
);

CREATE TABLE "Project" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "topic" text NOT NULL,
  "description" text,
  "project_goal" text,
  "work_scope" text,
  "needed_technologies" text,
  "created_at" timestamp with time zone NOT NULL,
  "max_groups" integer,
  "max_number_group_members" integer NOT NULL,
  "meeting_type_id" integer NOT NULL,
  "partnership_type" text,
  "language_doc" text NOT NULL,
  "notes" text,
  "priority" integer NOT NULL
);

CREATE TABLE "GroupRequests" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" integer NOT NULL,
  "project_id" integer,
  "student_id" integer,
  "created_by_user_id" integer NOT NULL,
  "status" text NOT NULL DEFAULT 'Pending',
  "type" text,
  "created_at" timestamp with time zone NOT NULL,
  "responded_at" timestamp with time zone
);

CREATE TABLE "Comments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "project_id" integer NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE "Responses" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "comment_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE "Groups" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "project_id" integer,
  "is_accepted" text,
  "leader_id" integer,
  "max_members" integer
);

CREATE TABLE "Students" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL UNIQUE,
  "group_id" integer,
  "email" text NOT NULL
);

CREATE TABLE "GroupFiles" (
  "group_id" integer NOT NULL,
  "file_id" uuid NOT NULL,
  PRIMARY KEY ("group_id", "file_id")
);

CREATE TABLE "CalendarEvents" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "time" timestamp with time zone NOT NULL,
  "group_id" integer NOT NULL,
  "name" text NOT NULL
);

CREATE TABLE "ProjectTags" (
  "project_id" integer NOT NULL,
  "tag_id" integer NOT NULL,
  PRIMARY KEY ("project_id", "tag_id")
);

CREATE TABLE "ProjectFiles" (
  "id" uuid PRIMARY KEY,
  "original_file_name" character varying(255) NOT NULL,
  "gcs_object_name" character varying(512) NOT NULL,
  "content_type" character varying(255) NOT NULL,
  "team_id" integer NOT NULL,
  "upload_date" timestamp with time zone NOT NULL
);

ALTER TABLE "Companies"
  ADD CONSTRAINT "FK_Companies_Users_user_id"
  FOREIGN KEY ("user_id") REFERENCES "Users" ("id") ON DELETE CASCADE;

ALTER TABLE "Files"
  ADD CONSTRAINT "FK_Files_Users_user_id"
  FOREIGN KEY ("user_id") REFERENCES "Users" ("id") ON DELETE CASCADE;

ALTER TABLE "Notifications"
  ADD CONSTRAINT "FK_Notifications_Users_user_id"
  FOREIGN KEY ("user_id") REFERENCES "Users" ("id") ON DELETE CASCADE;

ALTER TABLE "Notifications"
  ADD CONSTRAINT "FK_Notifications_GroupRequests_group_request_id"
  FOREIGN KEY ("group_request_id") REFERENCES "GroupRequests" ("id") ON DELETE SET NULL;

ALTER TABLE "Project"
  ADD CONSTRAINT "FK_Project_Companies_company_id"
  FOREIGN KEY ("company_id") REFERENCES "Companies" ("id") ON DELETE CASCADE;

ALTER TABLE "Project"
  ADD CONSTRAINT "FK_Project_Meeting_types_meeting_type_id"
  FOREIGN KEY ("meeting_type_id") REFERENCES "Meeting_types" ("id") ON DELETE RESTRICT;

ALTER TABLE "Comments"
  ADD CONSTRAINT "FK_Comments_Users_user_id"
  FOREIGN KEY ("user_id") REFERENCES "Users" ("id") ON DELETE CASCADE;

ALTER TABLE "Comments"
  ADD CONSTRAINT "FK_Comments_Project_project_id"
  FOREIGN KEY ("project_id") REFERENCES "Project" ("id") ON DELETE CASCADE;

ALTER TABLE "Responses"
  ADD CONSTRAINT "FK_Responses_Comments_comment_id"
  FOREIGN KEY ("comment_id") REFERENCES "Comments" ("id") ON DELETE CASCADE;

ALTER TABLE "Responses"
  ADD CONSTRAINT "FK_Responses_Users_user_id"
  FOREIGN KEY ("user_id") REFERENCES "Users" ("id") ON DELETE CASCADE;

ALTER TABLE "Groups"
  ADD CONSTRAINT "FK_Groups_Project_project_id"
  FOREIGN KEY ("project_id") REFERENCES "Project" ("id") ON DELETE SET NULL;

ALTER TABLE "Groups"
  ADD CONSTRAINT "FK_Groups_Students_leader_id"
  FOREIGN KEY ("leader_id") REFERENCES "Students" ("id") ON DELETE RESTRICT;

ALTER TABLE "Students"
  ADD CONSTRAINT "FK_Students_Users_user_id"
  FOREIGN KEY ("user_id") REFERENCES "Users" ("id") ON DELETE CASCADE;

ALTER TABLE "Students"
  ADD CONSTRAINT "FK_Students_Groups_group_id"
  FOREIGN KEY ("group_id") REFERENCES "Groups" ("id") ON DELETE SET NULL;

ALTER TABLE "GroupRequests"
  ADD CONSTRAINT "FK_GroupRequests_Groups_group_id"
  FOREIGN KEY ("group_id") REFERENCES "Groups" ("id") ON DELETE CASCADE;

ALTER TABLE "GroupRequests"
  ADD CONSTRAINT "FK_GroupRequests_Project_project_id"
  FOREIGN KEY ("project_id") REFERENCES "Project" ("id") ON DELETE SET NULL;

ALTER TABLE "GroupRequests"
  ADD CONSTRAINT "FK_GroupRequests_Students_student_id"
  FOREIGN KEY ("student_id") REFERENCES "Students" ("id") ON DELETE CASCADE;

ALTER TABLE "GroupRequests"
  ADD CONSTRAINT "FK_GroupRequests_Users_created_by_user_id"
  FOREIGN KEY ("created_by_user_id") REFERENCES "Users" ("id") ON DELETE CASCADE;

ALTER TABLE "GroupFiles"
  ADD CONSTRAINT "FK_GroupFiles_Groups_group_id"
  FOREIGN KEY ("group_id") REFERENCES "Groups" ("id") ON DELETE CASCADE;

ALTER TABLE "GroupFiles"
  ADD CONSTRAINT "FK_GroupFiles_Files_file_id"
  FOREIGN KEY ("file_id") REFERENCES "Files" ("id") ON DELETE CASCADE;

ALTER TABLE "CalendarEvents"
  ADD CONSTRAINT "FK_CalendarEvents_Groups_group_id"
  FOREIGN KEY ("group_id") REFERENCES "Groups" ("id") ON DELETE CASCADE;

ALTER TABLE "ProjectTags"
  ADD CONSTRAINT "FK_ProjectTags_Project_project_id"
  FOREIGN KEY ("project_id") REFERENCES "Project" ("id") ON DELETE CASCADE;

ALTER TABLE "ProjectTags"
  ADD CONSTRAINT "FK_ProjectTags_Tags_tag_id"
  FOREIGN KEY ("tag_id") REFERENCES "Tags" ("id") ON DELETE CASCADE;

CREATE INDEX "IX_Comments_project_id" ON "Comments" ("project_id");
CREATE INDEX "IX_Comments_user_id" ON "Comments" ("user_id");
CREATE INDEX "IX_Companies_user_id" ON "Companies" ("user_id");
CREATE INDEX "IX_Files_user_id" ON "Files" ("user_id");
CREATE INDEX "IX_GroupFiles_file_id" ON "GroupFiles" ("file_id");
CREATE INDEX "IX_Groups_leader_id" ON "Groups" ("leader_id");
CREATE INDEX "IX_Groups_project_id" ON "Groups" ("project_id");
CREATE INDEX "IX_Notifications_user_id" ON "Notifications" ("user_id");
CREATE INDEX "IX_Notifications_group_request_id" ON "Notifications" ("group_request_id");
CREATE INDEX "IX_Project_company_id" ON "Project" ("company_id");
CREATE INDEX "IX_Project_meeting_type_id" ON "Project" ("meeting_type_id");
CREATE INDEX "IX_ProjectTags_tag_id" ON "ProjectTags" ("tag_id");
CREATE INDEX "IX_GroupRequests_created_by_user_id" ON "GroupRequests" ("created_by_user_id");
CREATE INDEX "IX_GroupRequests_group_id" ON "GroupRequests" ("group_id");
CREATE INDEX "IX_GroupRequests_project_id" ON "GroupRequests" ("project_id");
CREATE INDEX "IX_GroupRequests_student_id" ON "GroupRequests" ("student_id");
CREATE INDEX "IX_Responses_comment_id" ON "Responses" ("comment_id");
CREATE INDEX "IX_Responses_user_id" ON "Responses" ("user_id");
CREATE INDEX "IX_Students_group_id" ON "Students" ("group_id");
CREATE INDEX "IX_Students_user_id" ON "Students" ("user_id");

-- Partial unique indexes to prevent duplicate pending requests
CREATE UNIQUE INDEX IF NOT EXISTS ux_group_invite_pending
  ON "GroupRequests"(group_id, student_id)
  WHERE type = 'Invitation' AND status = 'Pending';

CREATE UNIQUE INDEX IF NOT EXISTS ux_group_application_pending
  ON "GroupRequests"(group_id, student_id)
  WHERE type = 'Application' AND status = 'Pending';

CREATE UNIQUE INDEX IF NOT EXISTS ux_group_projectreq_pending
  ON "GroupRequests"(group_id, project_id)
  WHERE type = 'ProjectRequest' AND status = 'Pending' AND project_id IS NOT NULL;

-- Seed meeting types required by project FK (ids 1–3 match firma.html form)
INSERT INTO "Meeting_types" ("id", "type") VALUES
  (1, 'Online'),
  (2, 'Stacjonarne'),
  (3, 'Hybrydowe')
ON CONFLICT ("id") DO NOTHING;