services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached,z
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=projekt_db;Username=postgres;Password=postgres
 #     ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projekt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql:z

volumes:
  postgres_data: